// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwq2MXpVZ9TIq2ENtfsOoSKAzumKj3Htc',
    appId: '1:323405570637:android:836640c09d9a39ce3cf204',
    messagingSenderId: '323405570637',
    projectId: 'da1-bookstore',
    storageBucket: 'da1-bookstore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH5CH5fx80n91HsSxytQIZunO2UL1X5xM',
    appId: '1:323405570637:ios:3a9e1faae06067eb3cf204',
    messagingSenderId: '323405570637',
    projectId: 'da1-bookstore',
    storageBucket: 'da1-bookstore.appspot.com',
    androidClientId: '323405570637-13r4sof6h3ok56203r6udmgbsi0462tl.apps.googleusercontent.com',
    iosClientId: '323405570637-4mtvs30vu9msg7qfhojgal57b8bmr9s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookStoreManager',
  );
}
